[project]
name = "monorepo"
version = "0.1.0"
description = "A monorepo project."
license = "MIT"
authors = [
    { name = "Martynas Subonis", email = "martynas.subonis@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.12.3"

[dependency-groups]
dev = [
    "ruff==0.8.2",
]
