[project]
name = "package-a"
version = "0.1.0"
description = "Package \"a\" project."
license = "MIT"
authors = [
    { name = "Martynas Subonis", email = "martynas.subonis@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.12.3"

[dependency-groups]
dev = [
    "mypy==1.13.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.mypy]
strict = true
no_namespace_packages = true
ignore_missing_imports = true