name: Build and Dry Publish Packages

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-typing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [
          packages/package_a,
          packages/package_b
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3

      - name: Install dependencies using Poetry
        run: |
          cd ${{ matrix.directory }}
          poetry install

      - name: Run tests
        run: |
          cd ${{ matrix.directory }}
          poetry build

      - name: Run mypy
        run: |
          cd ${{ matrix.directory }}
          poetry publish --dry-run
