name: Build Packages For Mono-Repo Structure

on:
  pull_request:
    branches:
      - main

jobs:
  mono-repo-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    strategy:
      matrix:
        directory: [
          monorepo/packages/package_a,
          monorepo/packages/package_b
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: uv sync --frozen

      - name: uv build
        run: uv build
